apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: messaging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kangjuhyup/gaegaeting
    targetRevision: develop
    path: infra/k3s/applications/kafka/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
