apiVersion: v2
name: kafka
description: Kafka messaging for gaegaeting
type: application
version: 1.0.0
appVersion: "3.7"
dependencies:
  - name: kafka
    version: 26.4.3
    repository: https://charts.bitnami.com/bitnami
