apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "5.51.6"
    helm:
      releaseName: argocd
      values: |
        global:
          image:
            tag: "v2.9.3"

        controller:
          replicas: 1

        server:
          replicas: 2
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - argo.gaegaeting.app
            paths:
              - /
            pathType: Prefix
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argo.gaegaeting.app

          config:
            url: https://argo.gaegaeting.app
            application.instanceLabelKey: argocd.argoproj.io/instance
            users.anonymous.enabled: "false"
            repositories: |
              - type: git
                url: https://github.com/kangjuhyup/gaegaeting

          rbacConfig:
            policy.default: role:readonly

          # server.insecure=true를 명시적으로 켜서(현재 해결책) 307 루프 재발 방지
        configs:
          params:
            server.insecure: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

