apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-configmap.yaml
  - mysql-replication-init.yaml
  - mysql-master-svc.yaml
  - mysql-replica-svc.yaml
  - mysql-master-sts.yaml
  - mysql-replica-sts.yaml
