apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: app
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 2800
      targetPort: 2800
      protocol: TCP
      name: http
  selector:
    app: gateway
