apiVersion: v2
name: redis
description: Redis cache for gaegaeting
type: application
version: 1.0.0
appVersion: "7"
dependencies:
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
