apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: account-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: account-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: .*

