apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: kafka-secrets
    creationPolicy: Owner
  data:
    - secretKey: kafka-password
      remoteRef:
        key: KAFKA_PASSWORD
