apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: DATABASE_PASSWORD
    - secretKey: mysql-password
      remoteRef:
        key: DATABASE_PASSWORD
    - secretKey: mysql-replication-password
      remoteRef:
        key: DATABASE_PASSWORD
