apiVersion: v2
name: mysql
description: MySQL database for gaegaeting
type: application
version: 1.0.0
appVersion: "8.4"
dependencies:
  - name: mysql
    version: 9.14.4
    repository: https://charts.bitnami.com/bitnami
