import type { SqlMigration } from '@core/database';

export const initialMatchSchema: SqlMigration = {
  timestamp: 1788347664586,
  name: 'InitialMatchSchema1788347664586',
  expectedTables: ['feed_item', 'feed', 'pair', 'like', 'location', 'main_area'],
  manifest: { sha256: 'acd3e7de05eb8a49eb0ed06de5c3b60e0eaaed5887c5a118fa05af828cb63c0e' },
  statements: [
    { text: `CREATE TABLE "feed_item" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "target_user_id" character(26) NOT NULL, "feed_id" integer NOT NULL, "state" smallint NOT NULL, "show_at" TIMESTAMP WITH TIME ZONE, "action_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_fi_feed_user" UNIQUE ("feed_id", "target_user_id"), CONSTRAINT "PK_15e831e9beea6ca204556c64438" PRIMARY KEY ("id"))` },
    { text: `CREATE INDEX "ix_fi_feed_target" ON "feed_item" ("feed_id", "target_user_id")` },
    { text: `CREATE INDEX "ix_fi_candidate" ON "feed_item" ("target_user_id")` },
    { text: `CREATE TABLE "feed" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "user_id" character(26) NOT NULL, "date" character(8) NOT NULL, "slot" smallint NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "uq_feed_user_date_slot" UNIQUE ("user_id", "date", "slot"), CONSTRAINT "PK_8a8dfd1ff306ccdf65f0b5d04b2" PRIMARY KEY ("id"))` },
    { text: `CREATE INDEX "ix_feed_expires_at" ON "feed" ("expires_at")` },
    { text: `CREATE INDEX "ix_feed_date_slot" ON "feed" ("date", "slot")` },
    { text: `CREATE INDEX "ix_feed_user_date" ON "feed" ("user_id", "date")` },
    { text: `CREATE TABLE "pair" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "left_user_id" character(26) NOT NULL, "right_user_id" character(26) NOT NULL, "active" boolean NOT NULL DEFAULT true, "unmatched_at" TIMESTAMP WITH TIME ZONE, "like_a_id" integer, "like_b_id" integer, CONSTRAINT "uq_match_pair_active" UNIQUE ("left_user_id", "right_user_id", "active"), CONSTRAINT "PK_3eaf216329c5c50aedb94fa797e" PRIMARY KEY ("id"))` },
    { text: `CREATE INDEX "ix_match_like_b" ON "pair" ("like_b_id")` },
    { text: `CREATE INDEX "ix_match_like_a" ON "pair" ("like_a_id")` },
    { text: `CREATE INDEX "ix_match_right_active" ON "pair" ("right_user_id", "active", "id")` },
    { text: `CREATE INDEX "ix_match_left_active" ON "pair" ("left_user_id", "active", "id")` },
    { text: `CREATE TABLE "like" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "liker_id" character(26) NOT NULL, "likee_id" character(26) NOT NULL, "source" smallint NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_like_edge" UNIQUE ("liker_id", "likee_id"), CONSTRAINT "PK_eff3e46d24d416b52a7e0ae4159" PRIMARY KEY ("id"))` },
    { text: `CREATE INDEX "ix_like_outbox" ON "like" ("liker_id", "active", "id")` },
    { text: `CREATE INDEX "ix_like_inbox" ON "like" ("likee_id", "active", "id")` },
    { text: `CREATE TABLE "location" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" character(26) NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "city" character varying(100), "district" character varying(100), "location_point" point GENERATED ALWAYS AS (point(longitude, latitude)) STORED NOT NULL, CONSTRAINT "PK_ba3b695bc9d4bd35cc12839507f" PRIMARY KEY ("user_id"))` },
    { text: `CREATE INDEX "spx_location_point" ON "location" USING GiST ("location_point")` },
    { text: `CREATE INDEX "ix_lat_lng" ON "location" ("latitude", "longitude")` },
    { text: `CREATE TABLE "main_area" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" character varying NOT NULL, "code" character varying(64) NOT NULL, "name" character varying(100) NOT NULL, "parent_code" character varying(64), CONSTRAINT "PK_8301258e494b44a91917c921af4" PRIMARY KEY ("user_id"))` },
    { text: `CREATE INDEX "ix_main_area_parent" ON "main_area" ("parent_code")` },
    { text: `CREATE UNIQUE INDEX "uq_main_area_code" ON "main_area" ("code")` },
    { text: `ALTER TABLE "feed_item" ADD CONSTRAINT "FK_91ca417c3b6e110dfefa311f7df" FOREIGN KEY ("feed_id") REFERENCES "feed"("id") ON DELETE CASCADE ON UPDATE NO ACTION` },
    { text: `ALTER TABLE "pair" ADD CONSTRAINT "FK_7e3c5378bd648337c58d37639b4" FOREIGN KEY ("like_a_id") REFERENCES "like"("id") ON DELETE SET NULL ON UPDATE NO ACTION` },
    { text: `ALTER TABLE "pair" ADD CONSTRAINT "FK_3578c47763e9ed70bbedfbbf808" FOREIGN KEY ("like_b_id") REFERENCES "like"("id") ON DELETE SET NULL ON UPDATE NO ACTION` },
  ],
};
